application: skywars-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#- url: /_ah/spi/.*
#  script: main_api.APPLICATION
- url: .*
  script: main.app
#  secure: always

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
#- name: endpoints
#  version: 1.0
